### ISSUE TITLE
Beoordeling opdracht 1.2

### ISSUE THREAD

**Issue by chelseadoeleman** [ManoukK/browser-technologies-1920#1]
Hi!
*Een beschrijving van alle features die je hebt getest*
Super nice! Duidelijke beschrijvingen en heel fijn dat er afbeeldingen bij staan! 

*Beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben*
Duidelijke beschrijving. Lekker bezig! 

*Een beschrijving van de Devices en browsers waar je op hebt getest*
Je hebt op verschillende devices getest en netjes de browsers erbij geschreven! 

*Een beschrijving van de screenreader test*
Goed getest met de screenreader :)

**Comment by ManoukK** [comment]
Bedankt voor je issue! Ik heb een todo lijstje toegevoegd in de wiki waar ik de 8 features bespreek https://github.com/ManoukK/browser-technologies-1920/wiki/8-features-testen Het staat helemaal onderaan :D
